# Generated by Django 2.2 on 2021-11-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('station', models.CharField(max_length=200)),
                ('line', models.CharField(max_length=200)),
                ('admarea', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('id', models.CharField(max_length=2000, primary_key=True, serialize=False)),
            ],
        ),
    ]
