# Generated by Django 2.2 on 2021-11-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide_p', '0002_auto_20211120_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stations',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
