# Generated by Django 2.2 on 2021-11-20 08:49

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('guide_p', '0003_auto_20211120_0818'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stations',
            options={'ordering': (django.db.models.functions.text.Lower('station'),)},
        ),
    ]
